apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pms8-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target : "/"
spec:
  rules:
#  - host: huapms08.cloudns.cl
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tomcat-svc
            port:
              number: 80
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: tomcat-svc
#            port:
#              number: 443
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
#  tls:            
#    - hosts:
#      - huapms08.cloudns.cl
#      secretName: tls-secret
