kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"    
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  clusterIP: None
        #  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    #    type: LoadBalancer
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-ep
subsets:
  - addresses:
      - ip: 10.1.218.60
    ports:
      - port: 5432
---          
apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres-deployment
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: postgres
 template:
   metadata:
     labels:
       app: postgres
   spec:
     containers:
       - name: postgres
         image: postgres:11
         #         resources:
         #           limits:
         #             cpu: "2"
         #             memory: "4Gi"
         #           requests:
         #             cpu: "2"
         #             memory: "4Gi"
         ports:
           - containerPort: 5432
         env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-user
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pg-user
                  key: dbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-user
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
         volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgredb
     volumes:
       - name: postgredb
         persistentVolumeClaim:
           claimName: postgres-pvc
