apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  clusterIP: None
        #  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
# RedisInsight deployment with name 'redisinsight'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment #deployment name
  labels:
    app: redis #deployment label
spec:
  replicas: 1 #a single replica pod
  selector:
    matchLabels:
      app: redis #which pods is the deployment managing, as defined by the pod template
  template: #pod template
    metadata:
      labels:
        app: redis #label for pod/s
    spec:
      containers:

      - name:  redis #Container name (DNS_LABEL, unique)
#        image: redislabs/redisinsight:latest #repo/image
        image: redis
        imagePullPolicy: IfNotPresent #Always pull image
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
        ports:
        - containerPort: 6379 #exposed container port and protocol
          protocol: TCP
